# Generated by Django 5.0.6 on 2024-07-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_App', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
