# Generated by Django 5.0.6 on 2024-07-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_App', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
