# Generated by Django 5.0.6 on 2024-08-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_App', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('RAZORPAY', 'Razorpay')], default='COD', max_length=20),
        ),
    ]
